Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### Jenkins VM ###
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/bionic64"
    jenkins.vm.hostname = "jenkins"
	jenkins.vm.network "private_network", ip: "192.168.56.15"
	jenkins.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
	 vb.cpus = 1
	 end
	jenkins.vm.provision "shell", path: "jenkins.sh"
  end
  
### Nexus vm ###
   config.vm.define "nexus" do |nexus|
    nexus.vm.box = "geerlingguy/centos7"
    nexus.vm.hostname = "nexus"
    nexus.vm.network "private_network", ip: "192.168.56.16"
	nexus.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	 vb.cpus = 2
	 end
	nexus.vm.provision "shell", path: "nexus.sh" 
   end
   
### SonarQube vm  ####
  config.vm.define "sonarq" do |sonarq|
    sonarq.vm.box = "ubuntu/bionic64"
	sonarq.vm.hostname = "sonarq"
    sonarq.vm.network "private_network", ip: "192.168.56.17"
	sonarq.vm.provider "virtualbox" do |vb|
     vb.memory = "3072"
	 vb.cpus = 2
	 end	
	sonarq.vm.provision "shell", path: "sonarq.sh"
  end

end
